### ISSUE TITLE
ValueError: Unable to guess signature from an empty list

### ISSUE THREAD

**Issue by Hypfer** [coherence-project/Coherence#20]
I am using coherence from the repo in Debian Wheezy with the caja plugin found here https://github.com/Hypfer/Coherence/blob/develop/caja-plugin/coherence_upnp_play_extension.py

Sometimes it works, but most of the time caja throws this error:

Traceback (most recent call last):
  File "/home/hypfer/.local/share/caja-python/extensions/coherence_upnp_play_extension.py", line 176, in get_file_items
    devices = self.coherence.get_devices(dbus_interface=BUS_NAME)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
ValueError: Unable to guess signature from an empty list

**Comment by htgoebel** [comment]
This project is seeking a maintainer, see #33. If you want this to be fixed, please provide a pull-request or volunteer to maintain the project.
