### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by hololeap** [coherence-project/Coherence#26]
Using coherence built on latest maintain/0.6.x branch on KUbuntu.
I'm getting the following error when using the Ampache backend:

```
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: Traceback (most recent call last):
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 298, in connectionLost
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: protocol.connectionLost(reason)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 213, in connectionLost
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: self.factory._disconnectedDeferred.callback(None)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: self._startRunCallbacks(result)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: self._runCallbacks()
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: --- <exception caught here> ---
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: current.result = callback(current.result, *args, **kw)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/local/lib/python2.7/dist-packages/Coherence-0.6.7-py2.7.egg/coherence/upnp/core/soap_service.py", line 67, in _gotResult
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: encoding=None)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/local/lib/python2.7/dist-packages/Coherence-0.6.7-py2.7.egg/coherence/upnp/core/soap_lite.py", line 119, in build_soap_call
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: return preamble + ET.tostring(envelope, 'utf-8')
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: ElementTree(element).write(file, encoding, method=method)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: serialize(write, self._root, encoding, qnames, namespaces)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: _serialize_xml(write, e, encoding, qnames, None)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: _serialize_xml(write, e, encoding, qnames, None)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: _serialize_xml(write, e, encoding, qnames, None)
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: write(_escape_cdata(text, encoding))
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: return text.encode(encoding, "xmlcharrefreplace")
Apr 17 13:22:01 quantum-net-media-server coherence[5514]: exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 455109: ordinal not in range(128)


```

**Comment by htgoebel** [comment]
This project is seeking a maintainer, see #33. If you want this to be fixed, please provide a pull-request or volunteer to maintain the project.
