### ISSUE TITLE
coherence breakage with twisted-16.5.0

### ISSUE THREAD

**Issue by 0-wiz-0** [coherence-project/Coherence#29]
When building with python-2.7 and twisted 16.5.0, the build of 0.6.6.2 fails with:
````
Twisted >= 2.5 and Twisted.Web >= 2.5 are required. Please install them.
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from coherence import __version__
  File ".../net/coherence/work/Coherence-0.6.6.2/coherence/__init__.py", line 14, in <module>
    from twisted import version as twisted_version
  File "/usr/pkg/lib/python2.7/site-packages/twisted/__init__.py", line 23, in <module>
    from twisted._version import __version__ as version
  File "/usr/pkg/lib/python2.7/site-packages/twisted/_version.py", line 8, in <module>
    from incremental import Version
ImportError: No module named incremental
*** Error code 1
````

**Comment by 0-wiz-0** [comment]
This was a packaging problem with twisted in pkgsrc (missing dependency), which is now fixed. Nothing to do here, sorry for the wrong bug report.
